apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: borkarrohit/tekton-argocd:1
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30030
    name: http
  selector:
    app: app
